# Generated by Django 3.1.1 on 2020-10-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_article_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
