# Generated by Django 3.1.1 on 2020-10-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201020_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('address_ip', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('port', models.IntegerField(default=3306)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
