# Generated by Django 3.1.1 on 2020-11-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_projectsql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsql',
            name='project_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
